// src/components/TechIcon.js
// Maps skill / tool names to a logo and brand colour. Unknown names fall back to a generic glyph.
import React from 'react';
import {
  SiAmazonwebservices,
  SiAndroid,
  SiAngular,
  SiAnthropic,
  SiApachemaven,
  SiAppium,
  SiAzuredevops,
  SiCsharp,
  SiCucumber,
  SiCypress,
  SiDotnet,
  SiGit,
  SiGithubcopilot,
  SiGooglecloud,
  SiGraphql,
  SiJavascript,
  SiJenkins,
  SiJira,
  SiJunit5,
  SiLinux,
  SiMicrosoftazure,
  SiMicrosoftsqlserver,
  SiMongodb,
  SiOpenai,
  SiOpenjdk,
  SiPlaywright,
  SiPostman,
  SiPowershell,
  SiPytest,
  SiPython,
  SiRobotframework,
  SiSelenium,
  SiTypescript,
  SiUnity,
  SiUnrealengine,
  SiWebdriverio,
  SiWindows,
  SiXcode,
} from 'react-icons/si';
import {
  FiActivity,
  FiBarChart2,
  FiCheckSquare,
  FiClipboard,
  FiCode,
  FiCpu,
  FiDatabase,
  FiFileText,
  FiGitMerge,
  FiGlobe,
  FiLayers,
  FiLink,
  FiMonitor,
  FiRepeat,
  FiSearch,
  FiServer,
  FiShield,
  FiTarget,
  FiUsers,
  FiZap,
} from 'react-icons/fi';

const TEXT = 'var(--text)';
const ACCENT = 'var(--accent)';

const ICONS = {
  Playwright: [SiPlaywright, '#2ead33'],
  Cypress: [SiCypress, '#69d3a7'],
  'Cypress.io': [SiCypress, '#69d3a7'],
  Selenium: [SiSelenium, '#43b02a'],
  'Selenium Grid': [SiSelenium, '#43b02a'],
  WebdriverIO: [SiWebdriverio, '#ea5906'],
  TestNG: [FiCheckSquare, '#e5484d'],
  JUnit: [SiJunit5, '#25a162'],
  pytest: [SiPytest, '#0a9edc'],
  MSTest: [SiDotnet, '#7c5cff'],
  'Robot Framework': [SiRobotframework, '#00c0b5'],
  'Cucumber (BDD)': [SiCucumber, '#23d96c'],
  Cucumber: [SiCucumber, '#23d96c'],
  TypeScript: [SiTypescript, '#3178c6'],
  JavaScript: [SiJavascript, '#f7df1e'],
  Java: [SiOpenjdk, '#ed8b00'],
  Python: [SiPython, '#3776ab'],
  'C#': [SiCsharp, '#9b4f96'],
  SQL: [FiDatabase, '#cc2927'],
  'Agentic AI systems': [FiCpu, ACCENT],
  'AI agents': [FiZap, ACCENT],
  'AI Agents': [FiZap, ACCENT],
  'AI test generation (BDD/TDD)': [FiActivity, ACCENT],
  'Test pack generation': [FiLayers, ACCENT],
  Claude: [SiAnthropic, '#d97757'],
  Copilot: [SiGithubcopilot, TEXT],
  Codex: [SiOpenai, TEXT],
  'REST API testing': [FiServer, '#ff6c37'],
  'REST API': [FiServer, '#ff6c37'],
  Postman: [SiPostman, '#ff6c37'],
  GraphQL: [SiGraphql, '#e10098'],
  'Contract testing': [FiLink, ACCENT],
  'Contract Testing': [FiLink, ACCENT],
  'SQL Server': [SiMicrosoftsqlserver, '#cc2927'],
  MongoDB: [SiMongodb, '#47a248'],
  Jenkins: [SiJenkins, '#d24939'],
  'Azure DevOps': [SiAzuredevops, '#0078d7'],
  Git: [SiGit, '#f05032'],
  Maven: [SiApachemaven, '#c71a36'],
  JIRA: [SiJira, '#2684ff'],
  Allure: [FiBarChart2, '#ff9d00'],
  'Report Portal': [FiBarChart2, '#38b2ac'],
  Linux: [SiLinux, '#fcc624'],
  PowerShell: [SiPowershell, '#5391fe'],
  AWS: [SiAmazonwebservices, '#ff9900'],
  Azure: [SiMicrosoftazure, '#0089d6'],
  GCP: [SiGooglecloud, '#4285f4'],
  Appium: [SiAppium, '#ee376d'],
  XCUITest: [SiXcode, '#147efb'],
  WinAppDriver: [SiWindows, '#0078d6'],
  TestComplete: [FiMonitor, '#22a06b'],
  Android: [SiAndroid, '#3ddc84'],
  Angular: [SiAngular, '#dd0031'],
  Unity: [SiUnity, TEXT],
  'Unreal Engine': [SiUnrealengine, TEXT],
  Unreal: [SiUnrealengine, TEXT],
  'Test strategy': [FiTarget, ACCENT],
  'Test plans': [FiClipboard, ACCENT],
  Regression: [FiRepeat, ACCENT],
  Smoke: [FiZap, ACCENT],
  E2E: [FiGitMerge, ACCENT],
  'Cross-browser': [FiGlobe, ACCENT],
  'SIT/UAT': [FiUsers, ACCENT],
  'Defect triage': [FiSearch, ACCENT],
  'Agile/Scrum': [FiRepeat, ACCENT],
  Agile: [FiRepeat, ACCENT],
  'CI/CD': [FiGitMerge, ACCENT],
  OCR: [FiFileText, ACCENT],
  'Test Generation': [FiActivity, ACCENT],
  GenAI: [FiCpu, ACCENT],
  LLMs: [FiCpu, ACCENT],
  TDD: [FiShield, ACCENT],
  API: [FiServer, '#ff6c37'],
};

export const techMeta = (name) => {
  const [Icon, color] = ICONS[name] || [FiCode, ACCENT];
  return { Icon, color };
};

const TechIcon = ({ name, ...props }) => {
  const { Icon } = techMeta(name);
  return <Icon aria-hidden="true" {...props} />;
};

export default TechIcon;
